/**
 * Types for the materials/<character>/ registry: character identity, reference-image manifest,
 * and the clip provenance/QC index (clips.json). This is the schema — validated at runtime by
 * tools/materials-validate.ts — the same pattern this project already uses for project.json /
 * timeline.json (engine/types.ts + ProjectLoader.validate()) instead of a separate JSON Schema
 * layer.
 */

export type QcStatus = 'approved' | 'rejected' | 'pending';
export type ReviewedBy = 'human' | 'ai-assisted' | 'automated';

export interface HeroRange { start: number; end: number; score: number; tags: string[]; }

export interface CharacterManifest {
  schemaVersion: 1;
  id: string;
  name: string;
  status: 'active' | 'archived';
  identity: { genderPresentation: string; agePresentation: string; world: string; };
  visualAnchors: { face: string[]; eyes: string[]; hair: string[]; costume: string[]; accessories: string[]; silhouette: string[]; };
  styleKeywords: string[];
  colorPalette: { primary: string[]; secondary: string[]; accent: string[]; };
  continuityRules: string[];
  forbiddenChanges: string[];
  /** Generated by tools/materials-validate.ts — do not hand-edit. */
  currentInventorySummary: { approvedClips: number; missingShotTypes: string[]; };
  updatedAt: string;
}

export interface ReferenceImage {
  id: string;
  file: string;
  sha256: string;
  view: 'front' | 'left-45' | 'right-45' | 'back' | 'full-body';
  framing: 'portrait' | 'full-body';
  strengths: string[];
  recommendedFor: string[];
  avoidFor: string[];
  notes: string;
}

export interface ReferencesManifest {
  schemaVersion: 1;
  character: string;
  references: ReferenceImage[];
}

export interface ClipMedia {
  durationSeconds: number; width: number; height: number; fps: number;
  codec: string; pixelFormat: string; hasAudio: boolean;
  /** sha256 of the clip file — computed by tools/materials-validate.ts, not hand-edited. */
  sha256: string;
}

export interface ClipGeneration {
  generationId: string;
  providerTaskId: string;
  model: string;
  requestPath: string;
}

export interface ClipQc {
  status: QcStatus;
  reviewedAt: string;
  reviewedBy: ReviewedBy;
  notes: string;
  issues: string[];
  contactSheet: string;
}

export interface ClipUsedBy { project: string; sourceId: string; }

export interface Clip {
  id: string;
  file: string;
  shotType: string;
  media: ClipMedia;
  generation: ClipGeneration;
  sourceReferenceImages: string[];
  heroRanges: HeroRange[];
  qc: ClipQc;
  usedBy: ClipUsedBy[];
}

export interface ClipsRegistry {
  schemaVersion: 1;
  character: string;
  updatedAt: string;
  clips: Clip[];
}

export interface GenerationRequest {
  generationId: string;
  character: string;
  tool: 'image_to_video' | 'text_to_video' | 'image_to_image' | 'text_to_image';
  model: string;
  prompt: string;
  referenceImages: string[];
  arguments: Record<string, string>;
  submittedAt: string;
}

export interface GenerationResult {
  generationId: string;
  providerTaskId: string;
  status: 'succeeded' | 'failed';
  outputSha256: string;
  completedAt: string;
}
